Take nmos::resource as rvalue-reference (as it was before commit df0c4cc85a44841b386b710a23f33a4eba07b056), in order to workaround "error C2719: formal parameter with requested alignment of 8 won't be aligned" with Visual Studio 2015 when building for Win32, since the health member is an atomic variable
(cherry picked from commit ab033ab85b793e480064e7f066c4900494fcc2c2)