IS-12 support (#330)
* Create IS-12 websocket server

* Remove incorrect comment

* Add `control_protocol_ws_port` to node example config

* Use lock to protect websockets

* Fix to obtain the event_ws position from the ws_handlers

* Create Root block, Device manager and Class manager nmos resources

* Add readonly on Get propertry support.
Add callback to retrieve control classes from control_protocol_state

* Fix declaration of nmos::experimental::control_classes for Linux

* Move functions around

* Update IS-12 schemas

* Tidy up make_nc_class_manager

* Add NcObject's GetSequenceItem

* Fix GetSequenceItem and add GetSequenceLength

* Code tidy up

* Add SetSequenceItem, AddSequenceItem, RemoveSequenceItem, FindMembersByPath

* Fix AddSequenceItem

* Fix FindMembersByPath

* Add FindMembersByRole and FindMembersByClassId

* Add GetControlClass, and GetDataType

* Bump up ubuntu 14.04 to use python 3.7 to overcome
ERROR: module 'asyncio' has no attribute 'get_running_loop' and
CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team

* Fix ModuleNotFoundError: No module named '_ctypes'

* Fixing python3.7 install

* Bump up to python3.8

* Add NcIdentBeacon, NcReceiverMonitor and NcReceiverMonitorProtected

* Use control_protocol_ws_port to construct request URLs for the Control Protocol websocket, or negative to disable the control protocol features

* Remove unused code

* Fix find_members_by_path and write log on method

* Remove un-used code

* Add Log gate to method

* Move nc_class_id definition from control_protocol_resource to control_protocol_utils

* Add nested block examples

* Extract IS-12 version from the rx ws path

* Add helper functions to create non-standard control class, and general tidy up

* Use of nc_class_id struct and method_id struct for map key

* Remove un-used code

* Add support for allowing user to insert non-standard control class method handler

* Fix 'nmos::experimental::control_class' constructor initialization

* Fix indentation

* Use better error instead of `out of bounds`

* Add non-standard Example class based on nmos-device-control-mock

* Update log messages

* Fix is_nc_block()

* Tidy-up function signatures

* Add subscription support

* Update outdated IS-12 links

* Tidy up, less casting

* Add description to nc_object to simplify create nc_xxx class

* Move nc helper functions to nc utils

* look before accessing control_protocol_state

* pusback allows on NcBlock only

* Add control protocol unit tests

* Add more unit tests

* Add NcPropertyConstraintsNumber, NcPropertyConstraintsString, NcParameterConstraintsNumber, NcParameterConstraintsString datatypes

* Tidy up make_nc_class_descriptor

* Fix to handle empty NCP URL path

* Code fix to construct nc_property_changed_event_data, thanks for @maweit reviewing

* Insert root block resource to the model will also inserting all its nested control protocol resources to the model as suggested by @maweit

* Add IS-12 to Readme

* Add tounchpoint support and link Receiver-Monitor with IS-04/IS-05 Receiver

* Add new headers to makefile

* Set IS-12 nmos resource with relevant nmos::type

* Clean up on how to construct propertry changed event

* Add constraints support, see https://specs.amwa.tv/ms-05-02/branches/v1.0.x/docs/Constraints.html

* Update comments

* typo

* Add primitive types

* Add a simple temperature sensor example, which pumps out new temperature value in a time interval

* Fix non-standard class's method handing

* Remove un-used code and fix typo

* Test readonly on set_sequence_item and add_sequence_item

* Enhance level 0 datatype constraints validation

* Return property_deprecated(298) if property is marked as deprecated

* Code tidy-up

* Enhance non-standard example control method handlers, add level 2 and level 0 constraints implementation to example control

* Prevent comparsion warning

* Reject Set on non-sequence value to sequence property

* Fix runtime and property sequence constraints validation

* Add method parameters constriants validation, and check method deprecation

* Add comments

* No arguments object to those methods which do not require any arguments

* Add deprecated property and deprecated method to Example Control Class

* Add logging for contraints validation

* Add property changed callback to perform application-specific operations to complete the property changed

* Add authorization support to IS-12

* Prevent warning C26800

* Add ncp authorization field to IS-04 controls array of an NMOS Device

* Update comments

* Return parameter_error (417) instead of bad_oid (404) in event of bad role while doing find_members_by_path

* Add non-standard class method with the necessary parameters

* Update node config JSON to include is12_versions

* Apply suggestions from code review

Co-authored-by: jonathan-r-thorpe <64410119+jonathan-r-thorpe@users.noreply.github.com>

* Update Development/nmos-cpp-node/node_implementation.cpp

Co-authored-by: jonathan-r-thorpe <64410119+jonathan-r-thorpe@users.noreply.github.com>

* Remove commented out code

* Update comments

* Added Receiver Monitor Protected and Ident Beacon workers to control_protocol_resources

* Apply suggestions from code review

Co-authored-by: jonathan-r-thorpe <64410119+jonathan-r-thorpe@users.noreply.github.com>

* Typo

* Fix example_control to use the number within the level 2 runtime constraints

* Add nc_ident_beacon resource type

* Tidy up receiver_monitor, receiver_monitor_protected and ident_beacon resources

* Update Development/nmos/control_protocol_ws_api.cpp

Co-authored-by: jonathan-r-thorpe <64410119+jonathan-r-thorpe@users.noreply.github.com>

* Update Development/nmos/json_fields.h

Co-authored-by: jonathan-r-thorpe <64410119+jonathan-r-thorpe@users.noreply.github.com>

* Change varaible names and function names for better description

* Update IS-12 Readme

* Update IS-12 Readme

* Update Development/nmos/control_protocol_handlers.h

Co-authored-by: jonathan-r-thorpe <64410119+jonathan-r-thorpe@users.noreply.github.com>

---------

Co-authored-by: jonathan-r-thorpe <64410119+jonathan-r-thorpe@users.noreply.github.com>
Co-authored-by: Jonathan Thorpe (Sony) <Jonathan.Thorpe@sony.com>